name: Build and Push Docker Image (CI)

on:
  push:
    branches: [ main ]
    paths:
      - 'Microservices/**'

env:
  DOCKER_IMAGE: ahmednasrhassan/demo-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit short hash
        id: commit
        run: echo "short_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Microservices
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ steps.commit.outputs.short_hash }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

      - name: Update Kubernetes deployment
        run: |
          # Update the image tag in the deployment file
          sed -i "s|image: ${{ env.DOCKER_IMAGE }}:.*|image: ${{ env.DOCKER_IMAGE }}:${{ steps.commit.outputs.short_hash }}|" k8s-yaml/demo-app/deployment.yaml
          
          # Commit and push the changes
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s-yaml/demo-app/deployment.yaml
          git commit -m "Update deployment image to ${{ steps.commit.outputs.short_hash }}"
          git push
